language: php

php:
  - 7.2
  - 7.4

before_script:
  - composer install
  - composer self-update

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
