language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

before_script:
  - composer install
  - composer self-update

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
